import React from "react";
import Image from "next/image";
import Container from "../Container";
import SectionTitle from "../SectionTitle";
import Card from "../Cards/Card";
import { columns } from "@/constants";

type ColumnItem = {
  boldText: string;
  title: string;
};


export default function Rarity() {
  return (
    <section
      className="border-[16px] border-gray-900 bg-blue-300 bg-cover bg-fixed bg-center py-0 [background-image:none] md:py-32 md:[background-image:url('/images/diagrams.png')]"
      id="rarity"
    >
      <Container>
        <Card className="mx-auto flex max-w-[740px] flex-col items-start gap-5 max-sm:rounded-none">
          <div className="flex flex-col gap-2">
            <SectionTitle>Rarity</SectionTitle>
            <p>
              Each NFT is algorithmically generated by combining 170+ unique
              traits with varying rarity across categories.
            </p>
          </div>

          <div className="flex w-full flex-col items-stretch gap-6 md:flex-row">
            {columns.map(({ name, image, items }) => (
              <ColumnImage
                key={`column-${name}`}
                name={name}
                items={items}
                image={image}
              />
            ))}
          </div>
        </Card>
      </Container>
    </section>
  );
}

const ColumnImage = ({ name, image, imageAlt, items }: {
  name?: string;
  image?: string | null;
  imageAlt?: string;
  items?: ColumnItem[];
}) => {
  return (
    <div className="flex-1">
      <p className="mb-3 font-heading">{name}</p>

      <div className="flex h-full flex-col gap-2">
        {items?.map(({ boldText, title }, index) => (
          <div
            key={`item-${index}`}
            className="grid grid-cols-2 items-start rounded p-2 odd:bg-blue-50"
          >
            <p className="font-bold">{boldText}</p>
            <p>{title}</p>
          </div>
        ))}

        <div className="hidden h-full items-center justify-center md:flex">
          {image && (
            <div className="relative h-[270px] w-[318px]">
              <Image
                src={image || "No Image Provided"}
                alt={imageAlt || "No Alt Provided"}
                fill
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
