import type { Metadata } from "next"
import "./globals.css"
import { Space_Mono } from "next/font/google"
import { VisualEditing } from "next-sanity"
import { draftMode } from "next/headers"
import { ViewTransitions } from "next-view-transitions"
import PageWrapper from "@/components/PageWrapper"

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ViewTransitions>
      <html lang="en" className={spaceMono.variable}>
        <body>
          {draftMode().isEnabled && (
            <div>
              <a className="p-4 bg-blue-300 block" href="/api/disable-draft">
                Disable preview mode
              </a>
            </div>
          )}
          <PageWrapper>{children}</PageWrapper>

          {draftMode().isEnabled && <VisualEditing />}
        </body>
      </html>
    </ViewTransitions>
  )
}
